name: ci
on:
  push:
    branches:
      - main
jobs:
    main:
        name: Main job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              

            - name: Install dependencies
              run: |
                  npm install

            - name: test
              run: |
                  npm run test